services:

  ai-troubleshooter:
    build: .
    container_name: ai-troubleshooter

    ports:
      - "8000:8000"

    environment:
      OLLAMA_URL: http://ollama:11434/api/chat
      NAGIOSLOGFILE: /logs/nagios.log

    volumes:
      - nagios_logs:/logs:ro

    depends_on:
      ollama:
        condition: service_healthy
      nagios:
        condition: service_started

    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  ollama-init:
    image: ollama/ollama
    container_name: ollama-init

    depends_on:
      ollama:
        condition: service_healthy

    environment:
      OLLAMA_HOST: http://ollama:11434

    volumes:
      - ollama:/root/.ollama

    command: >
      pull qwen2.5:1.5b

    restart: "no"
  nagios:
    image: jasonrivers/nagios
    volumes: 
      - nagios_logs:/opt/nagios/var

volumes:
  ollama:
  nagios_logs: