services:

  ai-troubleshooter:
    build: .
    container_name: ai-troubleshooter

    ports:
      - "8000:8000"

    environment:
      OLLAMA_URL: http://ollama:11434/api/chat
      NAGIOSLOGFILE: /logs/nagios.log

    volumes:
      - /usr/local/nagios/var:/logs

    depends_on:
      - ollama

    restart: unless-stopped


  services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  ollama-init:
    image: ollama/ollama
    depends_on:
      - ollama
    volumes:
      - ollama:/root/.ollama
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 10
        ollama pull qwen2.5:1.5b

volumes:
  ollama:
